erDiagram
    WORKSPACE 1 to 1+ REPOSITORY: contains
    WORKSPACE 1 to 1+ CHANNEL: contains
    WORKSPACE {
        string name
    }
    REPOSITORY {
        string type
    }
    CHANNEL 0+ to 0+ REPOSITORY: notifies
    CHANNEL 1 to 0+ SUBSCRIPTION: has
    CHANNEL 1 to 0+ INVITATION: has
    CHANNEL {
        string type
    }
    SUBSCRIPTION
    SUBSCRIPTION {
        string[] subscribers
        string filter
    }
    INVITATION
    INVITATION {
        string[] recipients
        date expiresOn
    }
    USER one or zero to 1 WORKSPACE: has
    USER {
        string email
        string name
    }
    TEAM one or zero to 1 WORKSPACE: has
    TEAM one or zero to 1+ USER: contains
    TEAM {
        string name
    }
